// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCb1tF1a5dKTA2OeTYluynzhWXTw7TtNI',
    appId: '1:482708196126:web:d6b9e0338b8a451f3c970f',
    messagingSenderId: '482708196126',
    projectId: 'campusfind-14d86',
    authDomain: 'campusfind-14d86.firebaseapp.com',
    storageBucket: 'campusfind-14d86.firebasestorage.app',
    measurementId: 'G-N40N28CB6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaPEL2-cSmgIsY4yjRNSh6YI3khiO4BSw',
    appId: '1:482708196126:android:3546a3ff92e981da3c970f',
    messagingSenderId: '482708196126',
    projectId: 'campusfind-14d86',
    storageBucket: 'campusfind-14d86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKm_oS2T8L8Fzrxy6ScnkfbDxr_dlolsA',
    appId: '1:482708196126:ios:75dba905ede6f3c73c970f',
    messagingSenderId: '482708196126',
    projectId: 'campusfind-14d86',
    storageBucket: 'campusfind-14d86.firebasestorage.app',
    iosClientId: '482708196126-g29k5p9i7hrh4vh0p0cbvkeehb54gpc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusfind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKm_oS2T8L8Fzrxy6ScnkfbDxr_dlolsA',
    appId: '1:482708196126:ios:75dba905ede6f3c73c970f',
    messagingSenderId: '482708196126',
    projectId: 'campusfind-14d86',
    storageBucket: 'campusfind-14d86.firebasestorage.app',
    iosClientId: '482708196126-g29k5p9i7hrh4vh0p0cbvkeehb54gpc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusfind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCb1tF1a5dKTA2OeTYluynzhWXTw7TtNI',
    appId: '1:482708196126:web:f1e4a56b0bc56a4a3c970f',
    messagingSenderId: '482708196126',
    projectId: 'campusfind-14d86',
    authDomain: 'campusfind-14d86.firebaseapp.com',
    storageBucket: 'campusfind-14d86.firebasestorage.app',
    measurementId: 'G-PW06TC7MXK',
  );
}
