// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjlQNZRVpQeDD5nP6c4AfhwYurTJFlt7s',
    appId: '1:769376703725:web:1079a16be9588bf63068e4',
    messagingSenderId: '769376703725',
    projectId: 'campusfind-c7061',
    authDomain: 'campusfind-c7061.firebaseapp.com',
    storageBucket: 'campusfind-c7061.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnGAOuqm7ADXPIDCF51weBEgJpWvD36Kw',
    appId: '1:769376703725:android:b0d6d759063f94193068e4',
    messagingSenderId: '769376703725',
    projectId: 'campusfind-c7061',
    storageBucket: 'campusfind-c7061.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRfsJvKxR1ST1_-tpZbXINNHAwQF94YbE',
    appId: '1:769376703725:ios:6d206a7abe1104af3068e4',
    messagingSenderId: '769376703725',
    projectId: 'campusfind-c7061',
    storageBucket: 'campusfind-c7061.firebasestorage.app',
    iosBundleId: 'com.example.campusFind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRfsJvKxR1ST1_-tpZbXINNHAwQF94YbE',
    appId: '1:769376703725:ios:6d206a7abe1104af3068e4',
    messagingSenderId: '769376703725',
    projectId: 'campusfind-c7061',
    storageBucket: 'campusfind-c7061.firebasestorage.app',
    iosBundleId: 'com.example.campusFind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjlQNZRVpQeDD5nP6c4AfhwYurTJFlt7s',
    appId: '1:769376703725:web:b9415157806dcd3b3068e4',
    messagingSenderId: '769376703725',
    projectId: 'campusfind-c7061',
    authDomain: 'campusfind-c7061.firebaseapp.com',
    storageBucket: 'campusfind-c7061.firebasestorage.app',
  );
}
